### ISSUE TITLE
 Include LICENSE in the generated wheels

### ISSUE THREAD

**Issue by pradyunsg** [gsnedders/python-webencodings#28]
See https://github.com/cython/cython/pull/3982/files for an example of how to do so.

This is necessary since pip’s vendoring logic is being changed to allow using wheels preferentially. This means it would need to use a hard-coded URL for the license of this package, until this package adds a license directly.

**Comment by pfmoore** [comment]
Seems like this happened in #13 which has been merged (in 2017!) but no new release has happened since...

**Comment by pradyunsg** [comment]
Indeed. Closing in favour of https://github.com/gsnedders/python-webencodings/issues/27 then. :)
