### ISSUE TITLE
'utf8' encoding not found

### ISSUE THREAD

**Issue by AurangZ** [gsnedders/python-webencodings#8]
Pip version: 9.0.0
Python version: 2.7.12
Operating System: Ubuntu 16.04.1 LTS xenial
Description:

I tried to run Django makemessages with the latest version of pip and it gives me the following error
./lib/python2.7/site-packages/pip/_vendor/webencodings/init.py:1: Unknown encoding "utf8". Proceeding with ASCII instead.

```
xgettext: ./lib/python2.7/site-packages/pip/_vendor/webencodings/__init__.py:1: Unknown encoding "utf8". Proceeding with ASCII instead.
xgettext: Non-ASCII string at ./lib/python2.7/site-packages/pip/_vendor/webencodings/__init__.py:64.
          Please specify the source encoding through --from-code or through a comment
          as specified in http://www.python.org/peps/pep-0263.html.
```

**Comment by crdffrance** [comment]
Hello,

Any update about this issue ?

Thank you,

**Comment by letops** [comment]
This is so ironic...
The quickfix I always do is: in my local installations (**pip** includes this package), I replace every `# coding: utf8` for `# coding: utf-8`. It would be awesome if I didn't have to do this anymore.

**Comment by gsnedders** [comment]
This seems like a bug in xgettext; Python is well aware of the `utf8` encoding. Can you file a bug there?

**Comment by gsnedders** [comment]
Okay, reported at https://savannah.gnu.org/bugs/index.php?50357

**Comment by floreal797** [comment]
I still have this error with django makemessages.
pip 9.0.1
ubuntu 16.04

Downgrading to pip 8.1.2 solves the problem. So how to fix it?

**Comment by di** [comment]
@floreal797 This fix will be released in the next version of pip.

**Comment by davideghz** [comment]
as of today, the bug is still there!
